docs: add AWS-Billing & Slack Blog
linkall-labs/docs pull request #236
Opened 2023-01-30 14:29 UTC by ehino

Signed-off-by: Ehigiator Akhile <akhileehis@gmail.com>

### Related Issue

Solving Issue: #xxx

### PR Summary

### PR Type

- [ ] Fix typos or format(punctuation, space, indentation, code block, etc.)
- [ ] Update inappropriate or misunderstanding content
- [ ] Add missing content or new documents
- [ ] Delete useless content or outdated documents
- [ ] Localize or translate documents
- [ ] Deal with GitHub action files and scripts
- [ ] Deal with chores

2023-01-31 09:18 UTC, Michaelg22 requested changes

2023-01-31 09:40 UTC, ehino commented on blog/2023-01-30-awsbilling-slack-blog/index.md
> +The Slack sink connector handles incoming CloudEvents in a way that extracts the data part of the original event and delivers these extracted data to Slack channels. To set up Slack sink correctly, y
This is just an introduction to the Slack Sink
The process to created the Slack App is documented as well

2023-01-31 09:40 UTC, ehino commented on blog/2023-01-30-awsbilling-slack-blog/index.md
> +We will create the Slack sink connector first. The reason behind this is that the Source connector can only try to send CloudEvents 3 times only. If there is no Sink to receive the event, the operati
Okay

2023-02-01 03:13 UTC, Michaelg22 approved these changes

2023-02-01 03:13 UTC, merged