docs: add manag subscription doc
linkall-labs/docs pull request #47
Opened 2022-09-30 03:21 UTC by xdlbdy

Signed-off-by: delu <delu.xu@linkall.com>

2022-10-10 09:42 UTC, Michaelg22 requested changes

2022-10-10 09:42 UTC, Michaelg22 commented on user-manual/how-to/managing-subscription.md
> +This page describes how to manage Subscription in vanus using `vsctl subscription` command.
```suggestion
This page will teach you all you need to know to create and manage Subscriptions in Vanus.
```

2022-10-13 07:11 UTC, Michaelg22 requested changes

2022-10-13 07:11 UTC, Michaelg22 commented on user-manual/how-to/managing-subscription.md
> +# Managing Subscription
```suggestion
# Managing Subscriptions
```

2022-10-13 07:41 UTC, Michaelg22 approved these changes

2022-10-13 10:25 UTC, VedaGao approved these changes

2022-10-13 10:32 UTC, merged