s3-sink sns-source docs changed
linkall-labs/docs pull request #53
Opened 2022-10-09 09:42 UTC by SLyyq10

Signed-off-by: sling <18102030131@163.com>
A new pull request for these two docs because previous pull requests disappeared.
Docs both changed.

2022-10-09 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/linkall-labs/docs?pullRequest=53) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/linkall-labs/docs?pullRequest=53) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/linkall-labs/docs?pullRequest=53) it.</sub>

2022-10-10 09:10 UTC, Michaelg22 requested changes

2022-10-10 09:10 UTC, Michaelg22 commented on user-manual/connectors/sink/s3.md
> +At first, you can **pull the image** of S3 Sink from dockerhub like following command.
```suggestion
You can get the s3 Sink image from docker with the following command.
```

2022-10-10 09:10 UTC, Michaelg22 commented on user-manual/connectors/source/sns.md
> +You can use following command to pull a Display Connector's image from duckerhub.
```suggestion
You can use the following command to get the Display sink image.
```

2022-10-10 09:10 UTC, Michaelg22 commented on user-manual/connectors/source/sns.md
> +You can use following command to pull the SNS Source's image.
```suggestion
You can get the SNS Source by using the following command.
```

2022-10-12 12:56 UTC, VedaGao requested changes

2022-10-12 12:56 UTC, VedaGao commented on user-manual/connectors/source/sns.md
> +The `host.docker.internal` indicates docker's host ip. You can also use the ip address of **container** where Display Connector runs. Try following
```suggestion
The `host.docker.internal` indicates Docker's host IP. You can also use the IP address of **container** where Display Connector runs. Try following 
```

2022-10-12 12:56 UTC, VedaGao commented on user-manual/connectors/source/sns.md
> +command to get the ip address of container.
```suggestion
command to get the IP address of container.
```

2022-10-12 12:56 UTC, VedaGao commented on user-manual/connectors/source/sns.md
> +Use `docker ps` to get the Container id of Display Connector.
```suggestion
Use `docker ps` to get the Container ID of Display Connector.
```

2022-10-13 06:04 UTC, SLyyq10 commented on user-manual/connectors/sink/s3.md
> +receive CloudEvent success
The message is a response replied by S3 Sink and it doesn't have 's'.

2022-10-13 06:31 UTC, Michaelg22 requested changes

2022-10-13 06:31 UTC, Michaelg22 commented on user-manual/connectors/sink/s3.md
> +Create your `config.json` and `secret.json`, and mount them to specific paths to run the S3 Sink using following command.
```suggestion
After creating your 'config.json' and 'secret.json'  files, you can run the S3 Sink and mount the files with the following command.
```

2022-10-13 06:31 UTC, Michaelg22 commented on user-manual/connectors/sink/s3.md
> +To verify the S3 Sink, you should send CloudEvents to address of S3 Sink. Try to use following `curl` command.
```suggestion
To verify the S3 Sink, you should send CloudEvents to the address of S3 Sink. Try to use the  following `curl` command. 
```

2022-10-13 06:31 UTC, Michaelg22 commented on user-manual/connectors/source/sns.md
> +Create your `config.json` and `secret.json`, and mount them to specific paths to run the SNS source using following command.
```suggestion
After creating your 'config.json' and 'secret.json'  files, you can run the SNS source and mount the files with the following command.
```

2022-10-13 06:31 UTC, Michaelg22 commented on user-manual/connectors/source/sns.md
> +you should log in to the [AWS Management Console][aws-console] at first.Then visit the Simple Notification Service.
```suggestion
you should log in to the [AWS Management Console][aws-console] at first. Then visit the Simple Notification Service.
```

2022-10-13 06:31 UTC, Michaelg22 commented on user-manual/connectors/source/sns.md
> +Choose the SNS Topics, and then you can create topics or publish messages to topics.
```suggestion
Choose the SNS Topics, and then you can create topics or publish messages to the topics.
```

2022-10-21 05:02 UTC, Michaelg22 approved these changes

2022-10-31 06:43 UTC, closed without merging

2022-10-31 06:43 UTC, Michaelg22 commented
Made a new pr with the new structure of these two documents